# Generated by Django 3.1.1 on 2020-09-26 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='conatact',
            new_name='contact',
        ),
    ]
